### ISSUE TITLE
set log level doesn't work for standalone mode

### ISSUE THREAD

**Issue by Gordiievskyi** [browserup/browserup-proxy#302]
**Describe the bug**
Log level isn't set by yaml as documentation states [git docs](https://github.com/browserup/browserup-proxy#loggingl). 

First want to  say thanks for doing this great project.
Guys I realy need it to debug, I have a very strange errors when part of content is missing but info level do not show anything

**To Reproduce**
1. Download proxy zip
2. Unpack zip and navigate inside the folder
3. Navigate to `bin` folder.
4. Create `conf` folder
5. Create `bup-logging.yaml` with content:
```yaml
Configutation:
    name: Default
    Appenders:
      Console:
        name: Console_Appender
        target: SYSTEM_OUT
    Loggers:
      Root:
        level: warn
        AppenderRef:
          - ref: Console_Appender
      Logger:
        - name: com.browserup.bup
          level: warn
          AppenderRef:
            - ref: Console_Appender
```

6. Start you proxy `./browserup-proxy-2.0.1/bin/browserup-proxy`

Actual result:
`[INFO  2020-08-28T14:57:26,184 com.browserup.bup.proxy.Main]` - default info level still applied.

**Expected behavior**
no message appears and log level is warn

**Screenshots**

**Please complete the following information:**
 - OS: MAC OS 10.14.6
 - not applied
 - Version browserup-proxy-2.0.1

**Additional context**
Java 1.8.0_23
